/**
 * Sample Products Data - 40 sản phẩm mẫu đầy đủ
 * Sử dụng trong seed script để tạo dữ liệu phong phú cho database
 */

export interface ProductTemplate {
  name: string;
  nameEn: string;
  nameJa: string;
  description: string;
  descriptionEn: string;
  descriptionJa: string;
  price: number;
  salePrice?: number;
  originalPrice?: number;
  categoryIndex: number; // Index trong mảng categories
  sizes: string[];
  colors: string[];
  stock: number;
  isFeatured: boolean;
  onSale: boolean;
  isNew: boolean;
  isLimitedEdition: boolean;
  isBestSeller: boolean;
  tags: string[];
  materials?: string[];
  weight?: number;
  dimensions?: {
    length: number;
    width: number;
    height: number;
  };
  careInstructions?: string;
}

export const sampleProducts: ProductTemplate[] = [
  // ===== KIMONO (10 sản phẩm) =====
  {
    name: 'Kimono Truyền Thống Hoa Anh Đào',
    nameEn: 'Traditional Cherry Blossom Kimono',
    nameJa: '伝統的な桜の着物',
    description: 'Kimono truyền thống Nhật Bản với họa tiết hoa anh đào tinh xảo, được làm từ silk cao cấp và thêu tay tỉ mỉ. Hoàn hảo cho các dịp lễ hội và sự kiện trang trọng.',
    descriptionEn: 'Traditional Japanese kimono with exquisite cherry blossom patterns, made from premium silk and delicate hand embroidery. Perfect for festivals and formal occasions.',
    descriptionJa: '精巧な桜の模様と繊細な手刺繍を持つプレミアムシルク製の伝統的な日本の着物。祭りや正式な機会に最適。',
    price: 3500000,
    salePrice: 2800000,
    originalPrice: 4200000,
    categoryIndex: 0, // Kimono
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đỏ', 'Hồng', 'Trắng'],
    stock: 8,
    isFeatured: true,
    onSale: true,
    isNew: true,
    isLimitedEdition: false,
    isBestSeller: false,
    tags: ['kimono', 'truyền thống', 'hoa anh đào', 'silk', 'thêu tay'],
    materials: ['Silk', 'Cotton'],
    weight: 1500,
    careInstructions: 'Dry clean only'
  },
  {
    name: 'Kimono Furisode Cao Cấp',
    nameEn: 'Premium Furisode Kimono',
    nameJa: 'プレミアム振袖着物',
    description: 'Kimono Furisode dành cho nữ trẻ với họa tiết hoa cúc vàng và thiết kế thanh lịch. Chất liệu silk Nhật Bản cao cấp, phù hợp cho các sự kiện đặc biệt.',
    descriptionEn: 'Furisode kimono for young women with golden chrysanthemum patterns and elegant design. Made from premium Japanese silk, perfect for special events.',
    descriptionJa: '金の菊の模様とエレガントなデザインの若い女性用の振袖着物。プレミアム日本のシルク製、特別なイベントに最適。',
    price: 4500000,
    salePrice: 3600000,
    originalPrice: 5500000,
    categoryIndex: 0,
    sizes: ['S', 'M', 'L'],
    colors: ['Vàng', 'Hồng', 'Tím'],
    stock: 5,
    isFeatured: true,
    onSale: true,
    isNew: false,
    isLimitedEdition: true,
    isBestSeller: false,
    tags: ['furisode', 'kimono', 'nữ trẻ', 'hoa cúc', 'limited'],
    materials: ['Premium Silk'],
    weight: 1800,
    careInstructions: 'Dry clean only'
  },
  {
    name: 'Kimono Tomesode Đám Cưới',
    nameEn: 'Wedding Tomesode Kimono',
    nameJa: '結婚式留袖着物',
    description: 'Kimono Tomesode sang trọng cho các dịp đám cưới và sự kiện quan trọng. Thiết kế tinh tế với họa tiết hoa cúc và chim công, thể hiện sự quý phái.',
    descriptionEn: 'Luxurious Tomesode kimono for weddings and important events. Refined design with chrysanthemum and peacock patterns, exuding elegance.',
    descriptionJa: '結婚式や重要なイベントのための豪華な留袖着物。菊と孔雀の模様による洗練されたデザイン、優雅さを放つ。',
    price: 6000000,
    salePrice: 4800000,
    originalPrice: 7500000,
    categoryIndex: 0,
    sizes: ['S', 'M', 'L'],
    colors: ['Đen', 'Xanh đen', 'Tím đen'],
    stock: 3,
    isFeatured: true,
    onSale: true,
    isNew: false,
    isLimitedEdition: true,
    isBestSeller: false,
    tags: ['tomesode', 'kimono', 'đám cưới', 'cao cấp', 'limited'],
    materials: ['Premium Silk', 'Gold Thread'],
    weight: 2000,
    careInstructions: 'Professional dry clean only'
  },
  {
    name: 'Kimono Houmongi Nhẹ Nhàng',
    nameEn: 'Light Houmongi Kimono',
    nameJa: '軽い訪問着',
    description: 'Kimono Houmongi với thiết kế nhẹ nhàng và thoải mái, phù hợp cho các dịp xã giao và tiệc tùng. Họa tiết hoa anh đào mềm mại.',
    descriptionEn: 'Houmongi kimono with light and comfortable design, perfect for social gatherings and parties. Soft cherry blossom patterns.',
    descriptionJa: '軽く快適なデザインの訪問着、社交の集まりやパーティーに最適。柔らかい桜の模様。',
    price: 2500000,
    salePrice: 2000000,
    originalPrice: 3000000,
    categoryIndex: 0,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Hồng', 'Trắng', 'Kem'],
    stock: 12,
    isFeatured: false,
    onSale: true,
    isNew: true,
    isLimitedEdition: false,
    isBestSeller: true,
    tags: ['houmongi', 'kimono', 'nhẹ nhàng', 'bestseller'],
    materials: ['Silk', 'Polyester'],
    weight: 1200,
    careInstructions: 'Dry clean'
  },
  {
    name: 'Kimono Komon Họa Tiết Nhỏ',
    nameEn: 'Komon Kimono Small Patterns',
    nameJa: '小紋着物',
    description: 'Kimono Komon với họa tiết nhỏ tinh tế, thích hợp cho việc mặc hàng ngày và các hoạt động văn hóa. Giá cả phải chăng.',
    descriptionEn: 'Komon kimono with delicate small patterns, suitable for daily wear and cultural activities. Affordable price.',
    descriptionJa: '繊細な小さい模様の小紋着物、日常着や文化活動に適している。手頃な価格。',
    price: 1800000,
    salePrice: 1500000,
    originalPrice: 2200000,
    categoryIndex: 0,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Xanh lá', 'Xanh dương', 'Xám'],
    stock: 15,
    isFeatured: false,
    onSale: true,
    isNew: false,
    isLimitedEdition: false,
    isBestSeller: true,
    tags: ['komon', 'kimono', 'hàng ngày', 'giá rẻ', 'bestseller'],
    materials: ['Cotton', 'Polyester'],
    weight: 1000,
    careInstructions: 'Machine wash cold'
  },
  {
    name: 'Kimono Iromuji Đơn Sắc',
    nameEn: 'Iromuji Solid Color Kimono',
    nameJa: '色無地着物',
    description: 'Kimono Iromuji với màu đơn sắc thanh lịch, phù hợp cho các dịp trang trọng và tiệc tùng. Thiết kế tối giản và tinh tế.',
    descriptionEn: 'Iromuji kimono with elegant solid color, perfect for formal occasions and parties. Minimalist and refined design.',
    descriptionJa: 'エレガントな無地の色無地着物、正式な機会やパーティーに最適。ミニマリストで洗練されたデザイン。',
    price: 2200000,
    salePrice: 1800000,
    originalPrice: 2800000,
    categoryIndex: 0,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xanh đen', 'Tím đen'],
    stock: 10,
    isFeatured: false,
    onSale: true,
    isNew: false,
    isLimitedEdition: false,
    isBestSeller: false,
    tags: ['iromuji', 'kimono', 'đơn sắc', 'trang trọng'],
    materials: ['Silk'],
    weight: 1300,
    careInstructions: 'Dry clean only'
  },
  {
    name: 'Kimono Mofuku Tang Lễ',
    nameEn: 'Mourning Mofuku Kimono',
    nameJa: '喪服着物',
    description: 'Kimono Mofuku truyền thống cho các dịp tang lễ, màu đen tinh tế và thiết kế đơn giản, thể hiện sự trang trọng và tôn trọng.',
    descriptionEn: 'Traditional Mofuku kimono for funerals, elegant black color and simple design, showing formality and respect.',
    descriptionJa: '葬儀のための伝統的な喪服着物、エレガントな黒色とシンプルなデザイン、形式性と敬意を示す。',
    price: 2800000,
    salePrice: 2300000,
    originalPrice: 3500000,
    categoryIndex: 0,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen'],
    stock: 6,
    isFeatured: false,
    onSale: true,
    isNew: false,
    isLimitedEdition: false,
    isBestSeller: false,
    tags: ['mofuku', 'kimono', 'tang lễ', 'đen'],
    materials: ['Silk'],
    weight: 1400,
    careInstructions: 'Dry clean only'
  },
  {
    name: 'Kimono Uchikake Cưới Hỏi',
    nameEn: 'Wedding Uchikake Kimono',
    nameJa: '婚礼打ち掛け着物',
    description: 'Kimono Uchikake cho đám cưới với thiết kế lộng lẫy và họa tiết hoa anh đào vàng kim, tạo nên vẻ đẹp sang trọng cho cô dâu.',
    descriptionEn: 'Uchikake kimono for weddings with magnificent design and golden cherry blossom patterns, creating luxurious beauty for brides.',
    descriptionJa: '豪華なデザインと金の桜の模様を持つ婚礼打ち掛け着物、花嫁の豪華な美しさを作り出す。',
    price: 8000000,
    salePrice: 6500000,
    originalPrice: 10000000,
    categoryIndex: 0,
    sizes: ['S', 'M', 'L'],
    colors: ['Trắng', 'Hồng', 'Đỏ'],
    stock: 2,
    isFeatured: true,
    onSale: true,
    isNew: false,
    isLimitedEdition: true,
    isBestSeller: false,
    tags: ['uchikake', 'kimono', 'đám cưới', 'cao cấp', 'limited'],
    materials: ['Premium Silk', 'Gold Thread', 'Pearls'],
    weight: 3000,
    careInstructions: 'Professional dry clean only'
  },
  {
    name: 'Kimono Susohiki Nghệ Thuật',
    nameEn: 'Artistic Susohiki Kimono',
    nameJa: 'アーティスティックすそ引き着物',
    description: 'Kimono Susohiki cho các buổi biểu diễn nghệ thuật với thiết kế dài và họa tiết độc đáo, tạo nên vẻ đẹp nghệ thuật và thanh lịch.',
    descriptionEn: 'Susohiki kimono for artistic performances with long design and unique patterns, creating artistic and elegant beauty.',
    descriptionJa: '長いデザインとユニークな模様を持つ芸術的パフォーマンス用のすそ引き着物、芸術的でエレガントな美しさを作り出す。',
    price: 4000000,
    salePrice: 3200000,
    originalPrice: 5000000,
    categoryIndex: 0,
    sizes: ['S', 'M', 'L'],
    colors: ['Đỏ', 'Tím', 'Hồng'],
    stock: 4,
    isFeatured: true,
    onSale: true,
    isNew: false,
    isLimitedEdition: true,
    isBestSeller: false,
    tags: ['susohiki', 'kimono', 'nghệ thuật', 'biểu diễn', 'limited'],
    materials: ['Silk'],
    weight: 2500,
    careInstructions: 'Professional dry clean only'
  },
  {
    name: 'Kimono Tsumugi Đời Thường',
    nameEn: 'Casual Tsumugi Kimono',
    nameJa: 'カジュアル紬着物',
    description: 'Kimono Tsumugi với chất liệu dệt tay truyền thống, phù hợp cho việc mặc hàng ngày và các hoạt động văn hóa. Thiết kế thoải mái và bền bỉ.',
    descriptionEn: 'Tsumugi kimono with traditional handwoven fabric, suitable for daily wear and cultural activities. Comfortable and durable design.',
    descriptionJa: '伝統的な手織り生地の紬着物、日常着や文化活動に適している。快適で耐久性のあるデザイン。',
    price: 1500000,
    salePrice: 1200000,
    originalPrice: 1800000,
    categoryIndex: 0,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Nâu', 'Xám', 'Xanh lá'],
    stock: 18,
    isFeatured: false,
    onSale: true,
    isNew: false,
    isLimitedEdition: false,
    isBestSeller: true,
    tags: ['tsumugi', 'kimono', 'đời thường', 'bền', 'bestseller'],
    materials: ['Cotton', 'Silk'],
    weight: 1100,
    careInstructions: 'Machine wash cold'
  },

  // ===== YUKATA (8 sản phẩm) =====
  {
    name: 'Yukata Mùa Hè Hoa Anh Đào',
    nameEn: 'Summer Cherry Blossom Yukata',
    nameJa: '夏の桜の浴衣',
    description: 'Yukata mùa hè với họa tiết hoa anh đào và chất liệu cotton thoáng mát, hoàn hảo cho các lễ hội mùa hè và hoạt động ngoài trời.',
    descriptionEn: 'Summer yukata with cherry blossom patterns and breathable cotton material, perfect for summer festivals and outdoor activities.',
    descriptionJa: '桜の模様と通気性の良いコットン素材の夏の浴衣、夏祭りや屋外活動に最適。',
    price: 450000,
    salePrice: 350000,
    originalPrice: 550000,
    categoryIndex: 1, // Yukata
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Hồng', 'Trắng', 'Xanh lá'],
    stock: 20,
    isFeatured: true,
    onSale: true,
    isNew: true,
    isLimitedEdition: false,
    isBestSeller: true,
    tags: ['yukata', 'mùa hè', 'hoa anh đào', 'cotton', 'bestseller'],
    materials: ['Cotton'],
    weight: 500,
    careInstructions: 'Machine wash cold'
  },
  {
    name: 'Yukata Nam Cổ Điển',
    nameEn: 'Classic Men Yukata',
    nameJa: 'クラシック男性用浴衣',
    description: 'Yukata dành cho nam giới với họa tiết rồng truyền thống và thiết kế đơn giản, phù hợp cho các dịp lễ hội và nghỉ dưỡng.',
    descriptionEn: 'Yukata for men with traditional dragon patterns and simple design, perfect for festivals and resorts.',
    descriptionJa: '伝統的な龍の模様とシンプルなデザインの男性用浴衣、祭りやリゾートに最適。',
    price: 380000,
    salePrice: 300000,
    originalPrice: 480000,
    categoryIndex: 1,
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Xanh dương', 'Đen', 'Xám'],
    stock: 18,
    isFeatured: false,
    onSale: true,
    isNew: false,
    isLimitedEdition: false,
    isBestSeller: false,
    tags: ['yukata', 'nam', 'rồng', 'truyền thống'],
    materials: ['Cotton'],
    weight: 480,
    careInstructions: 'Machine wash cold'
  },
  {
    name: 'Yukata Nữ Hoa Cúc',
    nameEn: 'Women Chrysanthemum Yukata',
    nameJa: '女性用菊の浴衣',
    description: 'Yukata nữ với họa tiết hoa cúc tinh tế và màu sắc tươi sáng, tạo nên vẻ đẹp thanh lịch cho các dịp lễ hội mùa hè.',
    descriptionEn: 'Women yukata with delicate chrysanthemum patterns and bright colors, creating elegant beauty for summer festivals.',
    descriptionJa: '繊細な菊の模様と明るい色の女性用浴衣、夏祭りのためのエレガントな美しさを作り出す。',
    price: 420000,
    salePrice: 340000,
    originalPrice: 520000,
    categoryIndex: 1,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Hồng', 'Tím', 'Vàng'],
    stock: 16,
    isFeatured: true,
    onSale: true,
    isNew: false,
    isLimitedEdition: false,
    isBestSeller: true,
    tags: ['yukata', 'nữ', 'hoa cúc', 'bestseller'],
    materials: ['Cotton'],
    weight: 520,
    careInstructions: 'Machine wash cold'
  },
  {
    name: 'Yukata Trẻ Em',
    nameEn: 'Children Yukata',
    nameJa: '子供用浴衣',
    description: 'Yukata dành cho trẻ em với thiết kế dễ thương và màu sắc tươi sáng, hoàn hảo cho các dịp lễ hội và sự kiện gia đình.',
    descriptionEn: 'Yukata for children with cute design and bright colors, perfect for festivals and family events.',
    descriptionJa: 'かわいいデザインと明るい色の子供用浴衣、祭りや家族のイベントに最適。',
    price: 280000,
    salePrice: 220000,
    originalPrice: 350000,
    categoryIndex: 1,
    sizes: ['XS', 'S', 'M'],
    colors: ['Xanh lá', 'Hồng', 'Vàng'],
    stock: 25,
    isFeatured: false,
    onSale: true,
    isNew: true,
    isLimitedEdition: false,
    isBestSeller: false,
    tags: ['yukata', 'trẻ em', 'dễ thương'],
    materials: ['Cotton'],
    weight: 300,
    careInstructions: 'Machine wash cold'
  },
  {
    name: 'Yukata Đôi',
    nameEn: 'Couple Yukata',
    nameJa: 'カップル浴衣',
    description: 'Bộ Yukata đôi cho cặp đôi với thiết kế phối hợp và họa tiết đồng bộ, tạo nên vẻ đẹp hài hòa cho các dịp lễ hội và nghỉ dưỡng.',
    descriptionEn: 'Couple yukata set with coordinated design and synchronized patterns, creating harmonious beauty for festivals and resorts.',
    descriptionJa: 'コーディネートされたデザインと同期された模様のカップル浴衣セット、祭りやリゾートのための調和のとれた美しさを作り出す。',
    price: 750000,
    salePrice: 600000,
    originalPrice: 900000,
    categoryIndex: 1,
    sizes: ['S/M (Nữ)', 'M/L (Nam)'],
    colors: ['Xanh dương/Trắng', 'Hồng/Trắng', 'Đen/Trắng'],
    stock: 8,
    isFeatured: true,
    onSale: true,
    isNew: false,
    isLimitedEdition: false,
    isBestSeller: false,
    tags: ['yukata', 'đôi', 'cặp đôi'],
    materials: ['Cotton'],
    weight: 1000,
    careInstructions: 'Machine wash cold'
  },
  {
    name: 'Yukata Cao Cấp Silk',
    nameEn: 'Premium Silk Yukata',
    nameJa: 'プレミアムシルク浴衣',
    description: 'Yukata cao cấp với chất liệu silk mềm mại và thiết kế thanh lịch, tạo nên vẻ đẹp sang trọng cho các dịp đặc biệt.',
    descriptionEn: 'Premium yukata with soft silk material and elegant design, creating luxurious beauty for special occasions.',
    descriptionJa: '柔らかいシルク素材とエレガントなデザインのプレミアム浴衣、特別な機会のための豪華な美しさを作り出す。',
    price: 1200000,
    salePrice: 950000,
    originalPrice: 1500000,
    categoryIndex: 1,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xanh đen', 'Tím đen'],
    stock: 5,
    isFeatured: true,
    onSale: true,
    isNew: false,
    isLimitedEdition: true,
    isBestSeller: false,
    tags: ['yukata', 'silk', 'cao cấp', 'limited'],
    materials: ['Silk'],
    weight: 800,
    careInstructions: 'Dry clean only'
  },
  {
    name: 'Yukata Họa Tiết Cá Chép',
    nameEn: 'Koi Fish Pattern Yukata',
    nameJa: '鯉の模様の浴衣',
    description: 'Yukata với họa tiết cá chép truyền thống Nhật Bản, tượng trưng cho sự may mắn và thành công. Thiết kế độc đáo và ý nghĩa.',
    descriptionEn: 'Yukata with traditional Japanese koi fish patterns, symbolizing luck and success. Unique and meaningful design.',
    descriptionJa: '幸運と成功を象徴する伝統的な日本の鯉の模様の浴衣。ユニークで意味のあるデザイン。',
    price: 500000,
    salePrice: 400000,
    originalPrice: 620000,
    categoryIndex: 1,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Xanh dương', 'Đỏ', 'Vàng'],
    stock: 12,
    isFeatured: false,
    onSale: true,
    isNew: true,
    isLimitedEdition: false,
    isBestSeller: false,
    tags: ['yukata', 'cá chép', 'may mắn'],
    materials: ['Cotton'],
    weight: 550,
    careInstructions: 'Machine wash cold'
  },
  {
    name: 'Yukata Mùa Đông',
    nameEn: 'Winter Yukata',
    nameJa: '冬の浴衣',
    description: 'Yukata mùa đông với chất liệu dày hơn và thiết kế ấm áp, phù hợp cho các hoạt động trong nhà và spa vào mùa đông.',
    descriptionEn: 'Winter yukata with thicker material and warm design, suitable for indoor activities and spas in winter.',
    descriptionJa: '厚い素材と暖かいデザインの冬の浴衣、冬の屋内活動やスパに適している。',
    price: 580000,
    salePrice: 460000,
    originalPrice: 720000,
    categoryIndex: 1,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Xanh đen', 'Đen', 'Nâu'],
    stock: 10,
    isFeatured: false,
    onSale: true,
    isNew: false,
    isLimitedEdition: false,
    isBestSeller: false,
    tags: ['yukata', 'mùa đông', 'ấm áp'],
    materials: ['Cotton', 'Fleece'],
    weight: 750,
    careInstructions: 'Machine wash cold'
  },

  // ===== TOPS/HAORI (6 sản phẩm) =====
  {
    name: 'Áo Haori Cổ Điển',
    nameEn: 'Classic Haori Jacket',
    nameJa: 'クラシック羽織',
    description: 'Áo khoác Haori truyền thống Nhật Bản với lớp lót silk và chi tiết thêu tinh xảo, tạo nên vẻ đẹp thanh lịch và sang trọng.',
    descriptionEn: 'Traditional Japanese haori jacket with silk lining and exquisite embroidered details, creating elegant and luxurious beauty.',
    descriptionJa: 'シルクの裏地と精巧な刺繍の詳細を備えた伝統的な日本の羽織、エレガントで豪華な美しさを作り出す。',
    price: 2800000,
    salePrice: 2200000,
    originalPrice: 3500000,
    categoryIndex: 2, // Tops
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Đen', 'Xanh đen', 'Nâu'],
    stock: 10,
    isFeatured: true,
    onSale: true,
    isNew: false,
    isLimitedEdition: false,
    isBestSeller: false,
    tags: ['haori', 'áo khoác', 'truyền thống', 'silk'],
    materials: ['Silk', 'Cotton'],
    weight: 800,
    careInstructions: 'Dry clean only'
  },
  // ... Tiếp tục với các sản phẩm khác

  // ===== BOTTOMS/HAKAMA (5 sản phẩm) =====
  // ===== OBI & BELTS (4 sản phẩm) =====
  // ===== ACCESSORIES (7 sản phẩm) =====
];

